<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
    <HEAD>
        <meta http-equiv="content-type" content="text/html; charset=iso-8859-1">
        <TITLE>VegaDNS Administration</TITLE>
        <link rel="STYLESHEET" type="text/css" href="/css/core-style.css">
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
	<!--[if gte IE 5.5000]>
	<script type="text/javascript" src="/js/pngfix.js"></script>
	<![endif]-->

    </HEAD>
    <body background="/img/background.jpg">
     
<center>

<table border=0 width="100%">
    <tr valign="top">
<?php if($this->loggedIn()) {
// Display logged in/logout message
    $this->headScript()->captureStart();
?>
$(document).ready(function() {
    $('#logout').click(function(event) {
        event.preventDefault();
        $.post('/logout', {}, function(result) {
            if (result.success == true) {
                window.location = '/login';
            }
        });
    });
});
<?php $this->headScript()->captureEnd(); ?>
    <td width="25%">
    &nbsp;logged in as:<br>
    &nbsp;<b><?php echo $this->user->email ?></b><br>
    &nbsp<a id='logout' href="/logout">log out</a><br>
    </td>
<?php } ?>
    <td align="center">
    <img src="/img/vegadns.png" alt="VegaDNS">
    <br>tinydns administration - version <?php echo $this->version ?>
    </td>
<?php if($this->loggedIn()) { ?>
    <td width="25%">
    </td>
<?php } ?>
</tr>
</table>

<p>

<?php if($this->loggedIn()) {
// Display menu at top at all times now
?>

<table border=0>
    <tr>
        <td align="center">
            <a href="/domains">Domains</a>&nbsp | &nbsp
            <a href="/domains/add">New Domain</a>&nbsp | &nbsp
            <a href="/account">Edit My Account</a> | &nbsp
            <a href="/query">DNS Query</a>
        </td>
    </tr>

    <?php if ($this->user->isSeniorAdmin() || $this->user->isGroupAdmin()) { ?>
    <tr>
        <td align="center">
            <a href="/accounts">Accounts</a>&nbsp | &nbsp
            <a href="/accounts/add">Add Account</a>&nbsp | &nbsp
            <a href="/records/default">Default Records</a>&nbsp

        <?php if ($this->user->isSeniorAdmin()) { ?>
            | &nbsp <a href="/import">Import Domains via AXFR</a>&nbsp
        <?php } ?>
        </td>
    </tr>
    <?php } ?>
</table>
        </td>
    </tr>

</table>
<?php } ?>
<p>


    <br><?php echo $this->displayMsg() ?></b><br>
    <p>

<?php echo $this->layout()->content ?>


<?php if($this->loggedIn()) { ?>
    <p><a href="/">Main Menu</a>
<?php } ?>

</center>
<?php echo $this->headScript() ?>
</body>
</html>
