<a href="./?module={$module}&amp;scope=num">0-9</a> | 
<a href="./?module={$module}&amp;scope=a">A</a> | 
<a href="./?module={$module}&amp;scope=b">B</a> | 
<a href="./?module={$module}&amp;scope=c">C</a> | 
<a href="./?module={$module}&amp;scope=d">D</a> | 
<a href="./?module={$module}&amp;scope=e">E</a> | 
<a href="./?module={$module}&amp;scope=f">F</a> | 
<a href="./?module={$module}&amp;scope=g">G</a> | 
<a href="./?module={$module}&amp;scope=h">H</a> | 
<a href="./?module={$module}&amp;scope=i">I</a> | 
<a href="./?module={$module}&amp;scope=j">J</a> | 
<a href="./?module={$module}&amp;scope=k">K</a> | 
<a href="./?module={$module}&amp;scope=l">L</a> | 
<a href="./?module={$module}&amp;scope=m">M</a> | 
<a href="./?module={$module}&amp;scope=n">N</a> | 
<a href="./?module={$module}&amp;scope=o">O</a> | 
<a href="./?module={$module}&amp;scope=p">P</a> | 
<a href="./?module={$module}&amp;scope=q">Q</a> | 
<a href="./?module={$module}&amp;scope=r">R</a> | 
<a href="./?module={$module}&amp;scope=s">S</a> | 
<a href="./?module={$module}&amp;scope=t">T</a> | 
<a href="./?module={$module}&amp;scope=u">U</a> | 
<a href="./?module={$module}&amp;scope=v">V</a> | 
<a href="./?module={$module}&amp;scope=w">W</a> | 
<a href="./?module={$module}&amp;scope=x">X</a> | 
<a href="./?module={$module}&amp;scope=y">Y</a> | 
<a href="./?module={$module}&amp;scope=z">Z</a>
